//This Script is Generated by Sketch2AE
//
//contact: xixi@bigxixi.com
{
app.beginUndoGroup("DrawShape");
var compName_0 = "Artboard";
var compLength_0 = 15;
var compFPS_0 = 25;
var comp_0 = app.project.items.addComp(compName_0,5933,5770,1,compLength_0,compFPS_0);
comp_0.openInViewer();
var endMSG="Done !\n";
var newShape169 = comp_0.layers.addShape();
    newShape169.name = "Shape";
var shapeGroup169 = newShape169.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");
var SKShape169_53 = new Shape();
SKShape169_53.vertices = [[1672.32,-427.00000000000006],[1636.5000000000002,-427.00000000000006],[1636.5000000000002,-440.00000000000006],[1672.3,-440.00000000000006],];
SKShape169_53.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_53.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_53.closed = true;
var shapePathGroup169_53 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_53 = shapePathGroup169_53.property("ADBE Vector Shape");
    shapePath169_53.setValue(SKShape169_53);

shapePathGroup169_53.name = "Path";
var SKShape169_52 = new Shape();
SKShape169_52.vertices = [[1604.5600000000002,-427.00000000000006],[1568.76,-427.00000000000006],[1568.76,-440.00000000000006],[1604.5000000000002,-440.00000000000006],];
SKShape169_52.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_52.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_52.closed = true;
var shapePathGroup169_52 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_52 = shapePathGroup169_52.property("ADBE Vector Shape");
    shapePath169_52.setValue(SKShape169_52);

shapePathGroup169_52.name = "Path";
var SKShape169_51 = new Shape();
SKShape169_51.vertices = [[1536.7900000000002,-427.00000000000006],[1501.0000000000002,-427.00000000000006],[1501.0000000000002,-440.00000000000006],[1536.7900000000002,-440.00000000000006],];
SKShape169_51.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_51.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_51.closed = true;
var shapePathGroup169_51 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_51 = shapePathGroup169_51.property("ADBE Vector Shape");
    shapePath169_51.setValue(SKShape169_51);

shapePathGroup169_51.name = "Path";
var SKShape169_50 = new Shape();
SKShape169_50.vertices = [[1469.03,-427.00000000000006],[1433.24,-427.00000000000006],[1433.24,-440.00000000000006],[1469.03,-440.00000000000006],];
SKShape169_50.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_50.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_50.closed = true;
var shapePathGroup169_50 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_50 = shapePathGroup169_50.property("ADBE Vector Shape");
    shapePath169_50.setValue(SKShape169_50);

shapePathGroup169_50.name = "Path";
var SKShape169_49 = new Shape();
SKShape169_49.vertices = [[1401.2700000000002,-427.00000000000006],[1365.47,-427.00000000000006],[1365.47,-440.00000000000006],[1401.2700000000002,-440.00000000000006],];
SKShape169_49.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_49.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_49.closed = true;
var shapePathGroup169_49 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_49 = shapePathGroup169_49.property("ADBE Vector Shape");
    shapePath169_49.setValue(SKShape169_49);

shapePathGroup169_49.name = "Path";
var SKShape169_48 = new Shape();
SKShape169_48.vertices = [[1333.51,-427.00000000000006],[1297.7100000000003,-427.00000000000006],[1297.7100000000003,-440.00000000000006],[1333.5000000000002,-440.00000000000006],];
SKShape169_48.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_48.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_48.closed = true;
var shapePathGroup169_48 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_48 = shapePathGroup169_48.property("ADBE Vector Shape");
    shapePath169_48.setValue(SKShape169_48);

shapePathGroup169_48.name = "Path";
var SKShape169_47 = new Shape();
SKShape169_47.vertices = [[1265.7500000000002,-427.00000000000006],[1229.95,-427.00000000000006],[1229.95,-440.00000000000006],[1265.7500000000002,-440.00000000000006],];
SKShape169_47.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_47.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_47.closed = true;
var shapePathGroup169_47 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_47 = shapePathGroup169_47.property("ADBE Vector Shape");
    shapePath169_47.setValue(SKShape169_47);

shapePathGroup169_47.name = "Path";
var SKShape169_46 = new Shape();
SKShape169_46.vertices = [[1197.9800000000002,-427.00000000000006],[1162.1899999999998,-427.00000000000006],[1162.1899999999998,-440.00000000000006],[1197.9800000000002,-440.00000000000006],];
SKShape169_46.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_46.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_46.closed = true;
var shapePathGroup169_46 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_46 = shapePathGroup169_46.property("ADBE Vector Shape");
    shapePath169_46.setValue(SKShape169_46);

shapePathGroup169_46.name = "Path";
var SKShape169_45 = new Shape();
SKShape169_45.vertices = [[1130.22,-427.00000000000006],[1094.4199999999998,-427.00000000000006],[1094.4199999999998,-440.00000000000006],[1130.22,-440.00000000000006],];
SKShape169_45.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_45.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_45.closed = true;
var shapePathGroup169_45 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_45 = shapePathGroup169_45.property("ADBE Vector Shape");
    shapePath169_45.setValue(SKShape169_45);

shapePathGroup169_45.name = "Path";
var SKShape169_44 = new Shape();
SKShape169_44.vertices = [[1062.4600000000003,-427.00000000000006],[1026.66,-427.00000000000006],[1026.66,-440.00000000000006],[1062.4600000000003,-440.00000000000006],];
SKShape169_44.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_44.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_44.closed = true;
var shapePathGroup169_44 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_44 = shapePathGroup169_44.property("ADBE Vector Shape");
    shapePath169_44.setValue(SKShape169_44);

shapePathGroup169_44.name = "Path";
var SKShape169_43 = new Shape();
SKShape169_43.vertices = [[994.7,-427.00000000000006],[958.8999999999999,-427.00000000000006],[958.8999999999999,-440.00000000000006],[994.7,-440.00000000000006],];
SKShape169_43.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_43.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_43.closed = true;
var shapePathGroup169_43 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_43 = shapePathGroup169_43.property("ADBE Vector Shape");
    shapePath169_43.setValue(SKShape169_43);

shapePathGroup169_43.name = "Path";
var SKShape169_42 = new Shape();
SKShape169_42.vertices = [[926.9300000000001,-427.00000000000006],[891.1400000000001,-427.00000000000006],[891.1400000000001,-440.00000000000006],[926.9300000000001,-440.00000000000006],];
SKShape169_42.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_42.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_42.closed = true;
var shapePathGroup169_42 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_42 = shapePathGroup169_42.property("ADBE Vector Shape");
    shapePath169_42.setValue(SKShape169_42);

shapePathGroup169_42.name = "Path";
var SKShape169_41 = new Shape();
SKShape169_41.vertices = [[859.1699999999998,-427.00000000000006],[823.3799999999999,-427.00000000000006],[823.3799999999999,-440.00000000000006],[859.1699999999998,-440.00000000000006],];
SKShape169_41.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_41.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_41.closed = true;
var shapePathGroup169_41 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_41 = shapePathGroup169_41.property("ADBE Vector Shape");
    shapePath169_41.setValue(SKShape169_41);

shapePathGroup169_41.name = "Path";
var SKShape169_40 = new Shape();
SKShape169_40.vertices = [[791.4100000000001,-427.00000000000006],[755.6099999999999,-427.00000000000006],[755.6099999999999,-440.00000000000006],[791.4100000000001,-440.00000000000006],];
SKShape169_40.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_40.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_40.closed = true;
var shapePathGroup169_40 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_40 = shapePathGroup169_40.property("ADBE Vector Shape");
    shapePath169_40.setValue(SKShape169_40);

shapePathGroup169_40.name = "Path";
var SKShape169_39 = new Shape();
SKShape169_39.vertices = [[723.6499999999999,-427.00000000000006],[687.8500000000001,-427.00000000000006],[687.8500000000001,-440.00000000000006],[723.6499999999999,-440.00000000000006],];
SKShape169_39.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_39.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_39.closed = true;
var shapePathGroup169_39 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_39 = shapePathGroup169_39.property("ADBE Vector Shape");
    shapePath169_39.setValue(SKShape169_39);

shapePathGroup169_39.name = "Path";
var SKShape169_38 = new Shape();
SKShape169_38.vertices = [[655.8900000000001,-427.00000000000006],[620.0899999999999,-427.00000000000006],[620.0899999999999,-440.00000000000006],[655.8900000000001,-440.00000000000006],];
SKShape169_38.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_38.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_38.closed = true;
var shapePathGroup169_38 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_38 = shapePathGroup169_38.property("ADBE Vector Shape");
    shapePath169_38.setValue(SKShape169_38);

shapePathGroup169_38.name = "Path";
var SKShape169_37 = new Shape();
SKShape169_37.vertices = [[588.1200000000001,-427.00000000000006],[552.3,-427.00000000000006],[552.3,-440.00000000000006],[588.0899999999999,-440.00000000000006],];
SKShape169_37.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_37.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_37.closed = true;
var shapePathGroup169_37 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_37 = shapePathGroup169_37.property("ADBE Vector Shape");
    shapePath169_37.setValue(SKShape169_37);

shapePathGroup169_37.name = "Path";
var SKShape169_36 = new Shape();
SKShape169_36.vertices = [[520.3599999999999,-427.00000000000006],[484.5000000000002,-427.00000000000006],[484.5000000000002,-440.00000000000006],[520.2900000000002,-440.00000000000006],];
SKShape169_36.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_36.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_36.closed = true;
var shapePathGroup169_36 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_36 = shapePathGroup169_36.property("ADBE Vector Shape");
    shapePath169_36.setValue(SKShape169_36);

shapePathGroup169_36.name = "Path";
var SKShape169_35 = new Shape();
SKShape169_35.vertices = [[452.60000000000014,-427.00000000000006],[416.79999999999995,-427.00000000000006],[416.79999999999995,-440.00000000000006],[452.60000000000014,-440.00000000000006],];
SKShape169_35.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_35.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_35.closed = true;
var shapePathGroup169_35 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_35 = shapePathGroup169_35.property("ADBE Vector Shape");
    shapePath169_35.setValue(SKShape169_35);

shapePathGroup169_35.name = "Path";
var SKShape169_34 = new Shape();
SKShape169_34.vertices = [[384.8399999999999,-427.00000000000006],[349.0400000000002,-427.00000000000006],[349.0400000000002,-440.00000000000006],[384.8399999999999,-440.00000000000006],];
SKShape169_34.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_34.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_34.closed = true;
var shapePathGroup169_34 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_34 = shapePathGroup169_34.property("ADBE Vector Shape");
    shapePath169_34.setValue(SKShape169_34);

shapePathGroup169_34.name = "Path";
var SKShape169_33 = new Shape();
SKShape169_33.vertices = [[317.08000000000015,-427.00000000000006],[281.28,-427.00000000000006],[281.28,-440.00000000000006],[317.08000000000015,-440.00000000000006],];
SKShape169_33.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_33.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_33.closed = true;
var shapePathGroup169_33 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_33 = shapePathGroup169_33.property("ADBE Vector Shape");
    shapePath169_33.setValue(SKShape169_33);

shapePathGroup169_33.name = "Path";
var SKShape169_32 = new Shape();
SKShape169_32.vertices = [[249.31000000000017,-427.00000000000006],[213.50000000000023,-427.00000000000006],[213.50000000000023,-440.00000000000006],[249.2900000000002,-440.00000000000006],];
SKShape169_32.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_32.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_32.closed = true;
var shapePathGroup169_32 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_32 = shapePathGroup169_32.property("ADBE Vector Shape");
    shapePath169_32.setValue(SKShape169_32);

shapePathGroup169_32.name = "Path";
var SKShape169_31 = new Shape();
SKShape169_31.vertices = [[181.54999999999995,-427.00000000000006],[145.76,-427.00000000000006],[145.76,-440.00000000000006],[181.5,-440.00000000000006],];
SKShape169_31.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_31.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_31.closed = true;
var shapePathGroup169_31 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_31 = shapePathGroup169_31.property("ADBE Vector Shape");
    shapePath169_31.setValue(SKShape169_31);

shapePathGroup169_31.name = "Path";
var SKShape169_30 = new Shape();
SKShape169_30.vertices = [[113.78999999999996,-427.00000000000006],[77.99000000000001,-427.00000000000006],[77.99000000000001,-440.00000000000006],[113.78999999999996,-440.00000000000006],];
SKShape169_30.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_30.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_30.closed = true;
var shapePathGroup169_30 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_30 = shapePathGroup169_30.property("ADBE Vector Shape");
    shapePath169_30.setValue(SKShape169_30);

shapePathGroup169_30.name = "Path";
var SKShape169_29 = new Shape();
SKShape169_29.vertices = [[46.02999999999997,-427.00000000000006],[10.230000000000018,-427.00000000000006],[10.230000000000018,-440.00000000000006],[46.02999999999997,-440.00000000000006],];
SKShape169_29.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_29.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_29.closed = true;
var shapePathGroup169_29 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_29 = shapePathGroup169_29.property("ADBE Vector Shape");
    shapePath169_29.setValue(SKShape169_29);

shapePathGroup169_29.name = "Path";
var SKShape169_28 = new Shape();
SKShape169_28.vertices = [[-21.730000000000018,-427.00000000000006],[-57.52999999999997,-427.00000000000006],[-57.52999999999997,-440.00000000000006],[-21.730000000000018,-440.00000000000006],];
SKShape169_28.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_28.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_28.closed = true;
var shapePathGroup169_28 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_28 = shapePathGroup169_28.property("ADBE Vector Shape");
    shapePath169_28.setValue(SKShape169_28);

shapePathGroup169_28.name = "Path";
var SKShape169_27 = new Shape();
SKShape169_27.vertices = [[-89.5,-427.00000000000006],[-125.28999999999996,-427.00000000000006],[-125.28999999999996,-440.00000000000006],[-89.5,-440.00000000000006],];
SKShape169_27.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_27.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_27.closed = true;
var shapePathGroup169_27 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_27 = shapePathGroup169_27.property("ADBE Vector Shape");
    shapePath169_27.setValue(SKShape169_27);

shapePathGroup169_27.name = "Path";
var SKShape169_26 = new Shape();
SKShape169_26.vertices = [[-157.26,-427.00000000000006],[-193.05999999999995,-427.00000000000006],[-193.05999999999995,-440.00000000000006],[-157.26,-440.00000000000006],];
SKShape169_26.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_26.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_26.closed = true;
var shapePathGroup169_26 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_26 = shapePathGroup169_26.property("ADBE Vector Shape");
    shapePath169_26.setValue(SKShape169_26);

shapePathGroup169_26.name = "Path";
var SKShape169_25 = new Shape();
SKShape169_25.vertices = [[-225.01999999999998,-427.00000000000006],[-260.81999999999994,-427.00000000000006],[-260.81999999999994,-440.00000000000006],[-225.01999999999998,-440.00000000000006],];
SKShape169_25.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_25.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_25.closed = true;
var shapePathGroup169_25 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_25 = shapePathGroup169_25.property("ADBE Vector Shape");
    shapePath169_25.setValue(SKShape169_25);

shapePathGroup169_25.name = "Path";
var SKShape169_24 = new Shape();
SKShape169_24.vertices = [[-292.78,-427.00000000000006],[-328.5799999999999,-427.00000000000006],[-328.5799999999999,-440.00000000000006],[-292.78,-440.00000000000006],];
SKShape169_24.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_24.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_24.closed = true;
var shapePathGroup169_24 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_24 = shapePathGroup169_24.property("ADBE Vector Shape");
    shapePath169_24.setValue(SKShape169_24);

shapePathGroup169_24.name = "Path";
var SKShape169_23 = new Shape();
SKShape169_23.vertices = [[-360.54999999999995,-427.00000000000006],[-396.3399999999999,-427.00000000000006],[-396.3399999999999,-440.00000000000006],[-360.54999999999995,-440.00000000000006],];
SKShape169_23.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_23.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_23.closed = true;
var shapePathGroup169_23 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_23 = shapePathGroup169_23.property("ADBE Vector Shape");
    shapePath169_23.setValue(SKShape169_23);

shapePathGroup169_23.name = "Path";
var SKShape169_22 = new Shape();
SKShape169_22.vertices = [[-428.30999999999995,-427.00000000000006],[-464.0999999999999,-427.00000000000006],[-464.0999999999999,-440.00000000000006],[-428.30999999999995,-440.00000000000006],];
SKShape169_22.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_22.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_22.closed = true;
var shapePathGroup169_22 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_22 = shapePathGroup169_22.property("ADBE Vector Shape");
    shapePath169_22.setValue(SKShape169_22);

shapePathGroup169_22.name = "Path";
var SKShape169_21 = new Shape();
SKShape169_21.vertices = [[-496.06999999999994,-427.00000000000006],[-531.8699999999999,-427.00000000000006],[-531.8699999999999,-440.00000000000006],[-496.06999999999994,-440.00000000000006],];
SKShape169_21.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_21.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_21.closed = true;
var shapePathGroup169_21 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_21 = shapePathGroup169_21.property("ADBE Vector Shape");
    shapePath169_21.setValue(SKShape169_21);

shapePathGroup169_21.name = "Path";
var SKShape169_20 = new Shape();
SKShape169_20.vertices = [[-563.8299999999999,-427.00000000000006],[-599.6299999999999,-427.00000000000006],[-599.6299999999999,-440.00000000000006],[-563.8299999999999,-440.00000000000006],];
SKShape169_20.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_20.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_20.closed = true;
var shapePathGroup169_20 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_20 = shapePathGroup169_20.property("ADBE Vector Shape");
    shapePath169_20.setValue(SKShape169_20);

shapePathGroup169_20.name = "Path";
var SKShape169_19 = new Shape();
SKShape169_19.vertices = [[-631.5899999999999,-427.00000000000006],[-667.3899999999999,-427.00000000000006],[-667.3899999999999,-440.00000000000006],[-631.5899999999999,-440.00000000000006],];
SKShape169_19.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_19.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_19.closed = true;
var shapePathGroup169_19 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_19 = shapePathGroup169_19.property("ADBE Vector Shape");
    shapePath169_19.setValue(SKShape169_19);

shapePathGroup169_19.name = "Path";
var SKShape169_18 = new Shape();
SKShape169_18.vertices = [[-699.3599999999999,-427.00000000000006],[-735.1499999999999,-427.00000000000006],[-735.1499999999999,-440.00000000000006],[-699.3599999999999,-440.00000000000006],];
SKShape169_18.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_18.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_18.closed = true;
var shapePathGroup169_18 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_18 = shapePathGroup169_18.property("ADBE Vector Shape");
    shapePath169_18.setValue(SKShape169_18);

shapePathGroup169_18.name = "Path";
var SKShape169_17 = new Shape();
SKShape169_17.vertices = [[-767.1199999999999,-427.00000000000006],[-802.9099999999999,-427.00000000000006],[-802.9099999999999,-440.00000000000006],[-767.1199999999999,-440.00000000000006],];
SKShape169_17.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_17.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_17.closed = true;
var shapePathGroup169_17 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_17 = shapePathGroup169_17.property("ADBE Vector Shape");
    shapePath169_17.setValue(SKShape169_17);

shapePathGroup169_17.name = "Path";
var SKShape169_16 = new Shape();
SKShape169_16.vertices = [[-834.88,-427.00000000000006],[-870.68,-427.00000000000006],[-870.68,-440.00000000000006],[-834.88,-440.00000000000006],];
SKShape169_16.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_16.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_16.closed = true;
var shapePathGroup169_16 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_16 = shapePathGroup169_16.property("ADBE Vector Shape");
    shapePath169_16.setValue(SKShape169_16);

shapePathGroup169_16.name = "Path";
var SKShape169_15 = new Shape();
SKShape169_15.vertices = [[-902.64,-427.00000000000006],[-938.5,-427.00000000000006],[-938.5,-440.00000000000006],[-902.6999999999999,-440.00000000000006],];
SKShape169_15.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_15.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_15.closed = true;
var shapePathGroup169_15 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_15 = shapePathGroup169_15.property("ADBE Vector Shape");
    shapePath169_15.setValue(SKShape169_15);

shapePathGroup169_15.name = "Path";
var SKShape169_14 = new Shape();
SKShape169_14.vertices = [[-970.4,-427.00000000000006],[-1006.1999999999999,-427.00000000000006],[-1006.1999999999999,-440.00000000000006],[-970.4,-440.00000000000006],];
SKShape169_14.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_14.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_14.closed = true;
var shapePathGroup169_14 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_14 = shapePathGroup169_14.property("ADBE Vector Shape");
    shapePath169_14.setValue(SKShape169_14);

shapePathGroup169_14.name = "Path";
var SKShape169_13 = new Shape();
SKShape169_13.vertices = [[-1038.17,-427.00000000000006],[-1073.96,-427.00000000000006],[-1073.96,-440.00000000000006],[-1038.17,-440.00000000000006],];
SKShape169_13.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_13.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_13.closed = true;
var shapePathGroup169_13 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_13 = shapePathGroup169_13.property("ADBE Vector Shape");
    shapePath169_13.setValue(SKShape169_13);

shapePathGroup169_13.name = "Path";
var SKShape169_12 = new Shape();
SKShape169_12.vertices = [[-1105.9299999999998,-427.00000000000006],[-1141.73,-427.00000000000006],[-1141.73,-440.00000000000006],[-1105.9299999999998,-440.00000000000006],];
SKShape169_12.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_12.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_12.closed = true;
var shapePathGroup169_12 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_12 = shapePathGroup169_12.property("ADBE Vector Shape");
    shapePath169_12.setValue(SKShape169_12);

shapePathGroup169_12.name = "Path";
var SKShape169_11 = new Shape();
SKShape169_11.vertices = [[-1173.69,-427.00000000000006],[-1209.5,-427.00000000000006],[-1209.5,-440.00000000000006],[-1173.6999999999998,-440.00000000000006],];
SKShape169_11.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_11.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_11.closed = true;
var shapePathGroup169_11 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_11 = shapePathGroup169_11.property("ADBE Vector Shape");
    shapePath169_11.setValue(SKShape169_11);

shapePathGroup169_11.name = "Path";
var SKShape169_10 = new Shape();
SKShape169_10.vertices = [[-1241.4499999999998,-427.00000000000006],[-1277.25,-427.00000000000006],[-1277.25,-440.00000000000006],[-1241.5,-440.00000000000006],];
SKShape169_10.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_10.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_10.closed = true;
var shapePathGroup169_10 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_10 = shapePathGroup169_10.property("ADBE Vector Shape");
    shapePath169_10.setValue(SKShape169_10);

shapePathGroup169_10.name = "Path";
var SKShape169_9 = new Shape();
SKShape169_9.vertices = [[-1309.21,-427.00000000000006],[-1345.01,-427.00000000000006],[-1345.01,-440.00000000000006],[-1309.21,-440.00000000000006],];
SKShape169_9.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_9.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_9.closed = true;
var shapePathGroup169_9 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_9 = shapePathGroup169_9.property("ADBE Vector Shape");
    shapePath169_9.setValue(SKShape169_9);

shapePathGroup169_9.name = "Path";
var SKShape169_8 = new Shape();
SKShape169_8.vertices = [[-1376.98,-427.00000000000006],[-1412.8,-427.00000000000006],[-1412.8,-440.00000000000006],[-1377.01,-440.00000000000006],];
SKShape169_8.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_8.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_8.closed = true;
var shapePathGroup169_8 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_8 = shapePathGroup169_8.property("ADBE Vector Shape");
    shapePath169_8.setValue(SKShape169_8);

shapePathGroup169_8.name = "Path";
var SKShape169_7 = new Shape();
SKShape169_7.vertices = [[-1444.74,-427.00000000000006],[-1480.54,-427.00000000000006],[-1480.54,-440.00000000000006],[-1444.74,-440.00000000000006],];
SKShape169_7.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_7.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_7.closed = true;
var shapePathGroup169_7 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_7 = shapePathGroup169_7.property("ADBE Vector Shape");
    shapePath169_7.setValue(SKShape169_7);

shapePathGroup169_7.name = "Path";
var SKShape169_6 = new Shape();
SKShape169_6.vertices = [[-1512.5,-427.00000000000006],[-1548.3,-427.00000000000006],[-1548.3,-440.00000000000006],[-1512.5,-440.00000000000006],];
SKShape169_6.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_6.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_6.closed = true;
var shapePathGroup169_6 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_6 = shapePathGroup169_6.property("ADBE Vector Shape");
    shapePath169_6.setValue(SKShape169_6);

shapePathGroup169_6.name = "Path";
var SKShape169_5 = new Shape();
SKShape169_5.vertices = [[-1580.29,-427.00000000000006],[-1616.09,-427.00000000000006],[-1616.09,-440.00000000000006],[-1580.29,-440.00000000000006],];
SKShape169_5.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_5.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_5.closed = true;
var shapePathGroup169_5 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_5 = shapePathGroup169_5.property("ADBE Vector Shape");
    shapePath169_5.setValue(SKShape169_5);

shapePathGroup169_5.name = "Path";
var SKShape169_4 = new Shape();
SKShape169_4.vertices = [[-1648.06,-427.00000000000006],[-1683.85,-427.00000000000006],[-1683.85,-440.00000000000006],[-1648.06,-440.00000000000006],];
SKShape169_4.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_4.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_4.closed = true;
var shapePathGroup169_4 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_4 = shapePathGroup169_4.property("ADBE Vector Shape");
    shapePath169_4.setValue(SKShape169_4);

shapePathGroup169_4.name = "Path";
var SKShape169_3 = new Shape();
SKShape169_3.vertices = [[-1715.82,-427.00000000000006],[-1751.61,-427.00000000000006],[-1751.61,-440.00000000000006],[-1715.82,-440.00000000000006],];
SKShape169_3.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_3.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_3.closed = true;
var shapePathGroup169_3 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_3 = shapePathGroup169_3.property("ADBE Vector Shape");
    shapePath169_3.setValue(SKShape169_3);

shapePathGroup169_3.name = "Path";
var SKShape169_2 = new Shape();
SKShape169_2.vertices = [[-1783.58,-427.00000000000006],[-1819.3799999999999,-427.00000000000006],[-1819.3799999999999,-440.00000000000006],[-1783.58,-440.00000000000006],];
SKShape169_2.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_2.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_2.closed = true;
var shapePathGroup169_2 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_2 = shapePathGroup169_2.property("ADBE Vector Shape");
    shapePath169_2.setValue(SKShape169_2);

shapePathGroup169_2.name = "Path";
var SKShape169_1 = new Shape();
SKShape169_1.vertices = [[-1856.8,-455.44000000000005],[-1856.8,-381.68000000000006],[1691.05,-381.68000000000006],[1691.05,-455.44000000000005],];
SKShape169_1.inTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_1.outTangents = [[0,0],[0,0],[0,0],[0,0],];
SKShape169_1.closed = true;
var shapePathGroup169_1 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Group");
var shapePath169_1 = shapePathGroup169_1.property("ADBE Vector Shape");
    shapePath169_1.setValue(SKShape169_1);

shapePathGroup169_1.name = "Path";
var shapeFill169_0 = shapeGroup169.property("ADBE Vectors Group").addProperty("ADBE Vector Graphic - Fill");
    shapeFill169_0.enabled = 1;
    shapeFill169_0.blendMode.setValue(1);
    shapeFill169_0.property("ADBE Vector Fill Rule").setValue(1);
    shapeFill169_0.property("ADBE Vector Fill Opacity").setValue(100);
    shapeFill169_0.property("ADBE Vector Fill Color").setValue([0.04313725490196078,0.01176470588235294,0.2156862745098039,1]);
    shapeGroup169.property("ADBE Vector Transform Group").property("ADBE Vector Position").setValue([-82.87500000000023,-418.55999999999995]);
    shapeGroup169.property("ADBE Vector Transform Group").property("ADBE Vector Anchor").setValue([-82.87500000000023,-418.55999999999995]);
    newShape169.transform.opacity.setValue(100);
    shapeGroup169.property("ADBE Vector Transform Group").property("ADBE Vector Rotation").setValue(0);
endMSG += "Shape imported.";
app.endUndoGroup();
alert(endMSG);
}