//This Script is Generated by Sketch2AE
//
//contact: xixi@bigxixi.com
{
app.beginUndoGroup("DrawShape");
var compName_0 = "Artboard";
var compLength_0 = 8;
var compFPS_0 = 60;
var comp_0 = app.project.items.addComp(compName_0,3840,2603,1,compLength_0,compFPS_0);
comp_0.openInViewer();
var endMSG="Done !\n";
endMSG += "Shape imported.";
app.endUndoGroup();
alert(endMSG);
}